# Generated by Django 3.1.6 on 2021-03-17 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('duration', models.DurationField()),
                ('description', models.TextField()),
                ('rating', models.DecimalField(decimal_places=0, default=0, max_digits=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'recipe',
            },
        ),
        migrations.CreateModel(
            name='RecipeCategoryImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/recipe_category/')),
            ],
            options={
                'db_table': 'recipe_category_image',
            },
        ),
        migrations.CreateModel(
            name='RecipeImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/recipe/')),
                ('is_main', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'recipe_image',
            },
        ),
        migrations.CreateModel(
            name='RecipeSteps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.DecimalField(decimal_places=0, max_digits=2)),
                ('min_wait', models.DecimalField(decimal_places=0, default=0, max_digits=2)),
                ('sec_wait', models.DecimalField(decimal_places=0, default=0, max_digits=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipe.recipe')),
            ],
            options={
                'db_table': 'recipe_steps',
            },
        ),
        migrations.CreateModel(
            name='RecipeCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, unique=True)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipe.recipecategoryimage')),
            ],
            options={
                'db_table': 'recipe_category',
            },
        ),
        migrations.AddField(
            model_name='recipe',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='recipe.recipecategory'),
        ),
    ]
