# Generated by Django 3.1.6 on 2021-03-19 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0002_recipeprecaution'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RecipeImage',
        ),
        migrations.RemoveField(
            model_name='recipecategory',
            name='image',
        ),
        migrations.DeleteModel(
            name='RecipeCategoryImage',
        ),
    ]
