# Generated by Django 3.1.6 on 2021-03-22 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0004_auto_20210321_2359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipeprecaution',
            name='product',
        ),
    ]
