# Generated by Django 3.1.6 on 2021-03-23 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0007_recipesteps_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('quantity', models.DecimalField(decimal_places=0, default=1, max_digits=2)),
                ('weight', models.DecimalField(decimal_places=3, default=0, max_digits=6)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipe.recipe')),
            ],
            options={
                'db_table': 'recipe_ingredient',
            },
        ),
    ]
