# Generated by Django 3.1.6 on 2021-03-23 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0008_recipeingredient'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeProductName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, unique=True)),
            ],
            options={
                'db_table': 'recipe_product_name',
            },
        ),
        migrations.RemoveField(
            model_name='recipeingredient',
            name='name',
        ),
        migrations.AlterField(
            model_name='recipeprecaution',
            name='recipe',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='recipe.recipe'),
        ),
        migrations.AddField(
            model_name='recipeingredient',
            name='recipe_product_name',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.RESTRICT, to='recipe.recipeproductname'),
            preserve_default=False,
        ),
    ]
