# Generated by Django 3.1.6 on 2021-03-24 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0009_auto_20210323_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipesteps',
            name='min_wait',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=4),
        ),
    ]
