# Generated by Django 3.1.6 on 2021-03-25 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0010_auto_20210324_1957'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeingredient',
            name='litre',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='recipeingredient',
            name='spoon',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=5),
        ),
    ]
