# Generated by Django 3.1.6 on 2021-04-07 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20210407_0843'),
        ('recipe', '0012_recipeingredient_cup'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('meal', models.DecimalField(decimal_places=0, max_digits=1)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='recipe.recipe')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
            options={
                'db_table': 'recipe_schedule',
            },
        ),
    ]
