# Generated by Django 3.1.6 on 2021-04-10 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0014_auto_20210408_1938'),
    ]

    operations = [
        migrations.AddField(
            model_name='reciperating',
            name='feedback',
            field=models.CharField(default=' ', max_length=150),
            preserve_default=False,
        ),
    ]
