# Generated by Django 3.1.6 on 2021-04-13 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0016_auto_20210412_1032'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeMakeupCost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=6)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipe.recipeschedule')),
            ],
            options={
                'db_table': 'recipe_makeup_cost',
            },
        ),
    ]
