# Generated by Django 3.1.6 on 2021-04-24 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0017_recipemakeupcost'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RecipeMakeupCost',
        ),
    ]
