# Generated by Django 3.1.6 on 2021-04-22 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recipe', '0017_recipemakeupcost'),
        ('user', '0009_homeuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('schdule', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='recipe.recipeschedule')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='user.user')),
            ],
            options={
                'db_table': 'expense',
            },
        ),
        migrations.CreateModel(
            name='ExpenseUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expense.expense')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='user.user')),
            ],
            options={
                'db_table': 'expense_user',
            },
        ),
    ]
