# Generated by Django 3.1.6 on 2021-04-07 03:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_forgotpasswordtoken'),
    ]

    operations = [
        migrations.RenameField(
            model_name='forgotpasswordtoken',
            old_name='created_on',
            new_name='updated_at',
        ),
        migrations.AddField(
            model_name='forgotpasswordtoken',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
