# Generated by Django 3.1.6 on 2021-04-11 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20210407_0843'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeuser',
            name='is_root',
            field=models.BooleanField(default=False),
        ),
    ]
