# Generated by Django 3.1.6 on 2021-04-15 18:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_homeuser_is_root'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeuser',
            name='created_by',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homeuser',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
