# Generated by Django 3.1.6 on 2021-04-17 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_delete_homeuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_root', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='user.home')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='user.user')),
            ],
            options={
                'db_table': 'home_user',
            },
        ),
    ]
